---
title: "Spatial Experiment"
output: html_notebook
---

Let's load some libraries!
```{r}
library(tigris)
library(acs)
library(stringr)
library(dplyr)
library(leaflet)
```

Now we grab the spatial data using `tigris`

```{r}
counties <- c(5, 47, 61, 81, 85)
tracts <- tracts(state = 'NY', county = c(5, 47, 61, 81, 85), cb = TRUE)
```

Install the api key
```{r}
api.key.install(key = '118ee80eba3f9c1f025448a50887c4f8fe0badfa')
```

And now we get the tabular data
```{r}
geo <- geo.make(state = c('NY'), county = c(5, 47, 61, 81, 85), tract = "*")
income <- acs.fetch(endyear = 2012, span = 5, geography = geo, table.number = "B19001", col.names = "pretty")
```

We get a list
```{r}
names(attributes(income))
attr(income, "acs.colnames")
```

Turn it into a data.frame
```{r}
income_df <- data.frame(paste0(str_pad(income@geography$state, 2, "left", pad = "0"),
                               str_pad(income@geography$county, 3, "left", pad = "0"),
                               str_pad(income@geography$tract, 6, "left", pad = "0")),
                        income@estimate[,c("Household Income: Total:",
                                           "Household Income: $200,000 or more")],
                        stringsAsFactors = FALSE)
income_df <- select(income_df, 1:3)
rownames(income_df) <- 1:nrow(income_df)
names(income_df) <- c("GEOID", "total", "over_200")
income_df$percent <- 100*(income_df$over_200/income_df$total)
```

Merge with the spatial data
```{r}
income_merged <- geo_join(tracts, income_df, "GEOID", "GEOID")
income_merged <- income_merged[income_merged$ALAND>0,]
```

Make the map
```{r}
popup <- paste0("GEOID: ", income_merged$GEOID, "<br>", "Percent of Households above $200k: ", round(income_merged$percent,2))
pal <- colorNumeric( palette = "YlGnBu", domain = income_merged$percent)

map3<-leaflet() %>%
  addProviderTiles("CartoDB.Positron") %>%
  addPolygons(data = income_merged, 
              fillColor = ~pal(percent), 
              color = "#b2aeae", # you need to use hex colors
              fillOpacity = 0.7, 
              weight = 1, 
              smoothFactor = 0.2,
              popup = popup) %>%
  addLegend(pal = pal, 
            values = income_merged$percent, 
            position = "bottomright", 
            title = "Percent of Households<br>above $200k",
            labFormat = labelFormat(suffix = "%")) 
map3
```
